#!/usr/bin/env python
"""Generate src/pyroparse/_sport.py from the sport hierarchy.

Usage:
    python scripts/generate_sport.py

The generated file contains the Sport enum with all members explicitly defined,
precomputed hierarchy lookup tables, navigation methods, and classify_sport().
"""

from __future__ import annotations

import sys
from pathlib import Path

# Ensure the package is importable.
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from pyroparse._sport_categories import SPORT_CATEGORIES, flatten  # noqa: E402

TARGET = Path(__file__).resolve().parents[1] / "src" / "pyroparse" / "_sport.py"


def _enum_name(dotted: str) -> str:
    """Convert dot-notation value to UPPER_SNAKE enum name."""
    return dotted.replace(".", "_").upper()


def _parent_value(dotted: str) -> str | None:
    """Return the parent's dot-notation value, or None for roots."""
    parts = dotted.rsplit(".", 1)
    return parts[0] if len(parts) > 1 else None


def _root_value(dotted: str) -> str:
    """Return the root's dot-notation value."""
    return dotted.split(".")[0]


def generate() -> str:
    all_values = flatten(SPORT_CATEGORIES)

    lines: list[str] = []

    # --- Header ---
    lines.append('"""Hierarchical sport categorization.')
    lines.append("")
    lines.append("AUTO-GENERATED by scripts/generate_sport.py — DO NOT EDIT.")
    lines.append("Regenerate with:  python scripts/generate_sport.py")
    lines.append("")
    lines.append("Ported from SweatStack. Maps FIT sport/sub_sport values to a standardized")
    lines.append('dot-notation hierarchy (e.g. ``"cycling.road"``, ``"running.trail"``).')
    lines.append('"""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from enum import Enum")
    lines.append("")
    lines.append("")

    # --- Enum class ---
    lines.append("class Sport(str, Enum):")
    lines.append('    """Hierarchical sport enum with dot-notation values.')
    lines.append("")
    lines.append("    Examples::")
    lines.append("")
    lines.append('        Sport.CYCLING           # "cycling"')
    lines.append('        Sport.CYCLING_ROAD      # "cycling.road"')
    lines.append('        Sport.RUNNING_TRAIL     # "running.trail"')
    lines.append('    """')
    lines.append("")
    lines.append("    def __str__(self) -> str:")
    lines.append("        return self.value")
    lines.append("")

    # Members
    for val in all_values:
        lines.append(f'    {_enum_name(val)} = "{val}"')
    lines.append("")

    # --- Navigation methods ---
    lines.append("    def parent_sport(self) -> Sport | None:")
    lines.append('        """Return the immediate parent sport, or ``None`` for root sports."""')
    lines.append("        return _parent_of.get(self)")
    lines.append("")
    lines.append("    def root_sport(self) -> Sport:")
    lines.append('        """Return the root sport (self for root sports)."""')
    lines.append("        return _root_of[self]")
    lines.append("")
    lines.append("    def is_root_sport(self) -> bool:")
    lines.append('        """Return ``True`` if this is a root-level sport."""')
    lines.append("        return self not in _parent_of")
    lines.append("")
    lines.append(
        "    def is_sub_sport_of(self, sport: Sport | list[Sport] | tuple[Sport, ...]) -> bool:"
    )
    lines.append('        """Check whether this sport is a descendant of *sport*.')
    lines.append("")
    lines.append("        Accepts a single ``Sport`` or a list/tuple of ``Sport`` values.")
    lines.append('        """')
    lines.append("        if isinstance(sport, (list, tuple)):")
    lines.append("            return any(self in _descendants_of.get(s, _EMPTY) for s in sport)")
    lines.append("        return self in _descendants_of.get(sport, _EMPTY)")
    lines.append("")
    lines.append("    def display_name(self) -> str:")
    lines.append('        """Human-readable display name (e.g. ``"Cycling › Road"``)."""')
    lines.append('        return " \\u203a ".join(')
    lines.append('            p.replace("_", " ").title() for p in self.value.split(".")')
    lines.append("        )")
    lines.append("")
    lines.append("")

    # --- Lookup tables ---
    lines.append("_EMPTY: frozenset[Sport] = frozenset()")
    lines.append("")

    # _parent_of
    lines.append("_parent_of: dict[Sport, Sport] = {")
    for val in all_values:
        parent = _parent_value(val)
        if parent is not None:
            lines.append(f"    Sport.{_enum_name(val)}: Sport.{_enum_name(parent)},")
    lines.append("}")
    lines.append("")

    # _root_of
    lines.append("_root_of: dict[Sport, Sport] = {")
    for val in all_values:
        lines.append(f"    Sport.{_enum_name(val)}: Sport.{_enum_name(_root_value(val))},")
    lines.append("}")
    lines.append("")

    # _descendants_of — collect all descendants for each sport
    descendants: dict[str, list[str]] = {}
    for val in all_values:
        # Walk up the parent chain, adding self as descendant of each ancestor
        parts = val.split(".")
        for i in range(len(parts) - 1):
            ancestor = ".".join(parts[: i + 1])
            descendants.setdefault(ancestor, []).append(val)

    lines.append("_descendants_of: dict[Sport, frozenset[Sport]] = {")
    for ancestor, descs in descendants.items():
        members = ", ".join(f"Sport.{_enum_name(d)}" for d in descs)
        lines.append(f"    Sport.{_enum_name(ancestor)}: frozenset({{{members}}}),")
    lines.append("}")
    lines.append("")
    lines.append("")

    # --- classify_sport ---
    lines.append("def classify_sport(")
    lines.append("    sport: str | None,")
    lines.append("    sub_sport: str | None = None,")
    lines.append("    *,")
    lines.append("    has_gps: bool = False,")
    lines.append(") -> Sport:")
    lines.append('    """Map FIT sport/sub_sport strings to a :class:`Sport` category.')
    lines.append("")
    lines.append("    Uses the same heuristics as SweatStack: explicit sub_sport mappings")
    lines.append("    where possible, GPS presence as a tiebreaker for indoor/outdoor.")
    lines.append('    """')
    lines.append("    match sport:")
    lines.append('        case "cycling":')
    lines.append("            match sub_sport:")
    lines.append('                case "indoor_cycling":')
    lines.append("                    return Sport.CYCLING_TRAINER")
    lines.append('                case "road":')
    lines.append("                    return Sport.CYCLING_ROAD")
    lines.append('                case "mountain" | "downhill":')
    lines.append("                    return Sport.CYCLING_MOUNTAINBIKE")
    lines.append('                case "cyclocross":')
    lines.append("                    return Sport.CYCLING_CYCLOCROSS")
    lines.append('                case "track_cycling":')
    lines.append("                    return Sport.CYCLING_TRACK")
    lines.append('                case "gravel":')
    lines.append("                    return Sport.CYCLING_GRAVEL")
    lines.append("                case _:")
    lines.append("                    return Sport.CYCLING_ROAD if has_gps else Sport.CYCLING")
    lines.append('        case "running":')
    lines.append("            match sub_sport:")
    lines.append('                case "treadmill":')
    lines.append("                    return Sport.RUNNING_TREADMILL")
    lines.append('                case "track":')
    lines.append("                    return Sport.RUNNING_TRACK")
    lines.append('                case "trail":')
    lines.append("                    return Sport.RUNNING_TRAIL")
    lines.append("                case _:")
    lines.append("                    return Sport.RUNNING_ROAD if has_gps else Sport.RUNNING")
    lines.append('        case "walking":')
    lines.append("            return Sport.WALKING")
    lines.append('        case "hiking":')
    lines.append("            return Sport.WALKING_HIKING")
    lines.append('        case "swimming":')
    lines.append("            return Sport.SWIMMING")
    lines.append('        case "cross_country_skiing":')
    lines.append('            if sub_sport == "skate_skiing":')
    lines.append("                return Sport.CROSS_COUNTRY_SKIING_SKATE")
    lines.append("            return Sport.CROSS_COUNTRY_SKIING_CLASSIC")
    lines.append('        case "rowing":')
    lines.append('            if sub_sport == "indoor_rowing":')
    lines.append("                return Sport.ROWING_ERGOMETER")
    lines.append("            return Sport.ROWING")
    lines.append('        case "e_biking":')
    lines.append("            return Sport.CYCLING_ROAD if has_gps else Sport.CYCLING")
    lines.append('        case "generic":')
    lines.append("            return Sport.GENERIC")
    lines.append("        case _:")
    lines.append("            return Sport.UNKNOWN")

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    code = generate()
    TARGET.write_text(code)
    print(f"Generated {TARGET}")
