"""Hierarchical sport categorization.

AUTO-GENERATED by scripts/generate_sport.py — DO NOT EDIT.
Regenerate with:  python scripts/generate_sport.py

Ported from SweatStack. Maps FIT sport/sub_sport values to a standardized
dot-notation hierarchy (e.g. ``"cycling.road"``, ``"running.trail"``).
"""

from __future__ import annotations

from enum import Enum


class Sport(str, Enum):
    """Hierarchical sport enum with dot-notation values.

    Examples::

        Sport.CYCLING           # "cycling"
        Sport.CYCLING_ROAD      # "cycling.road"
        Sport.RUNNING_TRAIL     # "running.trail"
    """

    def __str__(self) -> str:
        return self.value

    CYCLING = "cycling"
    CYCLING_ROAD = "cycling.road"
    CYCLING_TT = "cycling.tt"
    CYCLING_CYCLOCROSS = "cycling.cyclocross"
    CYCLING_GRAVEL = "cycling.gravel"
    CYCLING_MOUNTAINBIKE = "cycling.mountainbike"
    CYCLING_TRACK = "cycling.track"
    CYCLING_TRACK_250M = "cycling.track.250m"
    CYCLING_TRACK_333M = "cycling.track.333m"
    CYCLING_TRAINER = "cycling.trainer"
    RUNNING = "running"
    RUNNING_ROAD = "running.road"
    RUNNING_TRACK = "running.track"
    RUNNING_TRACK_200M = "running.track.200m"
    RUNNING_TRACK_400M = "running.track.400m"
    RUNNING_TRAIL = "running.trail"
    RUNNING_TREADMILL = "running.treadmill"
    WALKING = "walking"
    WALKING_HIKING = "walking.hiking"
    CROSS_COUNTRY_SKIING = "cross_country_skiing"
    CROSS_COUNTRY_SKIING_CLASSIC = "cross_country_skiing.classic"
    CROSS_COUNTRY_SKIING_SKATE = "cross_country_skiing.skate"
    CROSS_COUNTRY_SKIING_BACKCOUNTRY = "cross_country_skiing.backcountry"
    CROSS_COUNTRY_SKIING_ERGOMETER = "cross_country_skiing.ergometer"
    ROWING = "rowing"
    ROWING_ERGOMETER = "rowing.ergometer"
    ROWING_INDOOR = "rowing.indoor"
    ROWING_REGATTA = "rowing.regatta"
    ROWING_FIXED_SEAT = "rowing.fixed_seat"
    ROWING_COASTAL = "rowing.coastal"
    SWIMMING = "swimming"
    SWIMMING_POOL = "swimming.pool"
    SWIMMING_POOL_50M = "swimming.pool.50m"
    SWIMMING_POOL_25M = "swimming.pool.25m"
    SWIMMING_POOL_25Y = "swimming.pool.25y"
    SWIMMING_POOL_33M = "swimming.pool.33m"
    SWIMMING_OPEN_WATER = "swimming.open_water"
    SWIMMING_FLUME = "swimming.flume"
    GENERIC = "generic"
    UNKNOWN = "unknown"

    def parent_sport(self) -> Sport | None:
        """Return the immediate parent sport, or ``None`` for root sports."""
        return _parent_of.get(self)

    def root_sport(self) -> Sport:
        """Return the root sport (self for root sports)."""
        return _root_of[self]

    def is_root_sport(self) -> bool:
        """Return ``True`` if this is a root-level sport."""
        return self not in _parent_of

    def is_sub_sport_of(self, sport: Sport | list[Sport] | tuple[Sport, ...]) -> bool:
        """Check whether this sport is a descendant of *sport*.

        Accepts a single ``Sport`` or a list/tuple of ``Sport`` values.
        """
        if isinstance(sport, (list, tuple)):
            return any(self in _descendants_of.get(s, _EMPTY) for s in sport)
        return self in _descendants_of.get(sport, _EMPTY)

    def display_name(self) -> str:
        """Human-readable display name (e.g. ``"Cycling › Road"``)."""
        return " \u203a ".join(
            p.replace("_", " ").title() for p in self.value.split(".")
        )


_EMPTY: frozenset[Sport] = frozenset()

_parent_of: dict[Sport, Sport] = {
    Sport.CYCLING_ROAD: Sport.CYCLING,
    Sport.CYCLING_TT: Sport.CYCLING,
    Sport.CYCLING_CYCLOCROSS: Sport.CYCLING,
    Sport.CYCLING_GRAVEL: Sport.CYCLING,
    Sport.CYCLING_MOUNTAINBIKE: Sport.CYCLING,
    Sport.CYCLING_TRACK: Sport.CYCLING,
    Sport.CYCLING_TRACK_250M: Sport.CYCLING_TRACK,
    Sport.CYCLING_TRACK_333M: Sport.CYCLING_TRACK,
    Sport.CYCLING_TRAINER: Sport.CYCLING,
    Sport.RUNNING_ROAD: Sport.RUNNING,
    Sport.RUNNING_TRACK: Sport.RUNNING,
    Sport.RUNNING_TRACK_200M: Sport.RUNNING_TRACK,
    Sport.RUNNING_TRACK_400M: Sport.RUNNING_TRACK,
    Sport.RUNNING_TRAIL: Sport.RUNNING,
    Sport.RUNNING_TREADMILL: Sport.RUNNING,
    Sport.WALKING_HIKING: Sport.WALKING,
    Sport.CROSS_COUNTRY_SKIING_CLASSIC: Sport.CROSS_COUNTRY_SKIING,
    Sport.CROSS_COUNTRY_SKIING_SKATE: Sport.CROSS_COUNTRY_SKIING,
    Sport.CROSS_COUNTRY_SKIING_BACKCOUNTRY: Sport.CROSS_COUNTRY_SKIING,
    Sport.CROSS_COUNTRY_SKIING_ERGOMETER: Sport.CROSS_COUNTRY_SKIING,
    Sport.ROWING_ERGOMETER: Sport.ROWING,
    Sport.ROWING_INDOOR: Sport.ROWING,
    Sport.ROWING_REGATTA: Sport.ROWING,
    Sport.ROWING_FIXED_SEAT: Sport.ROWING,
    Sport.ROWING_COASTAL: Sport.ROWING,
    Sport.SWIMMING_POOL: Sport.SWIMMING,
    Sport.SWIMMING_POOL_50M: Sport.SWIMMING_POOL,
    Sport.SWIMMING_POOL_25M: Sport.SWIMMING_POOL,
    Sport.SWIMMING_POOL_25Y: Sport.SWIMMING_POOL,
    Sport.SWIMMING_POOL_33M: Sport.SWIMMING_POOL,
    Sport.SWIMMING_OPEN_WATER: Sport.SWIMMING,
    Sport.SWIMMING_FLUME: Sport.SWIMMING,
}

_root_of: dict[Sport, Sport] = {
    Sport.CYCLING: Sport.CYCLING,
    Sport.CYCLING_ROAD: Sport.CYCLING,
    Sport.CYCLING_TT: Sport.CYCLING,
    Sport.CYCLING_CYCLOCROSS: Sport.CYCLING,
    Sport.CYCLING_GRAVEL: Sport.CYCLING,
    Sport.CYCLING_MOUNTAINBIKE: Sport.CYCLING,
    Sport.CYCLING_TRACK: Sport.CYCLING,
    Sport.CYCLING_TRACK_250M: Sport.CYCLING,
    Sport.CYCLING_TRACK_333M: Sport.CYCLING,
    Sport.CYCLING_TRAINER: Sport.CYCLING,
    Sport.RUNNING: Sport.RUNNING,
    Sport.RUNNING_ROAD: Sport.RUNNING,
    Sport.RUNNING_TRACK: Sport.RUNNING,
    Sport.RUNNING_TRACK_200M: Sport.RUNNING,
    Sport.RUNNING_TRACK_400M: Sport.RUNNING,
    Sport.RUNNING_TRAIL: Sport.RUNNING,
    Sport.RUNNING_TREADMILL: Sport.RUNNING,
    Sport.WALKING: Sport.WALKING,
    Sport.WALKING_HIKING: Sport.WALKING,
    Sport.CROSS_COUNTRY_SKIING: Sport.CROSS_COUNTRY_SKIING,
    Sport.CROSS_COUNTRY_SKIING_CLASSIC: Sport.CROSS_COUNTRY_SKIING,
    Sport.CROSS_COUNTRY_SKIING_SKATE: Sport.CROSS_COUNTRY_SKIING,
    Sport.CROSS_COUNTRY_SKIING_BACKCOUNTRY: Sport.CROSS_COUNTRY_SKIING,
    Sport.CROSS_COUNTRY_SKIING_ERGOMETER: Sport.CROSS_COUNTRY_SKIING,
    Sport.ROWING: Sport.ROWING,
    Sport.ROWING_ERGOMETER: Sport.ROWING,
    Sport.ROWING_INDOOR: Sport.ROWING,
    Sport.ROWING_REGATTA: Sport.ROWING,
    Sport.ROWING_FIXED_SEAT: Sport.ROWING,
    Sport.ROWING_COASTAL: Sport.ROWING,
    Sport.SWIMMING: Sport.SWIMMING,
    Sport.SWIMMING_POOL: Sport.SWIMMING,
    Sport.SWIMMING_POOL_50M: Sport.SWIMMING,
    Sport.SWIMMING_POOL_25M: Sport.SWIMMING,
    Sport.SWIMMING_POOL_25Y: Sport.SWIMMING,
    Sport.SWIMMING_POOL_33M: Sport.SWIMMING,
    Sport.SWIMMING_OPEN_WATER: Sport.SWIMMING,
    Sport.SWIMMING_FLUME: Sport.SWIMMING,
    Sport.GENERIC: Sport.GENERIC,
    Sport.UNKNOWN: Sport.UNKNOWN,
}

_descendants_of: dict[Sport, frozenset[Sport]] = {
    Sport.CYCLING: frozenset({Sport.CYCLING_ROAD, Sport.CYCLING_TT, Sport.CYCLING_CYCLOCROSS, Sport.CYCLING_GRAVEL, Sport.CYCLING_MOUNTAINBIKE, Sport.CYCLING_TRACK, Sport.CYCLING_TRACK_250M, Sport.CYCLING_TRACK_333M, Sport.CYCLING_TRAINER}),
    Sport.CYCLING_TRACK: frozenset({Sport.CYCLING_TRACK_250M, Sport.CYCLING_TRACK_333M}),
    Sport.RUNNING: frozenset({Sport.RUNNING_ROAD, Sport.RUNNING_TRACK, Sport.RUNNING_TRACK_200M, Sport.RUNNING_TRACK_400M, Sport.RUNNING_TRAIL, Sport.RUNNING_TREADMILL}),
    Sport.RUNNING_TRACK: frozenset({Sport.RUNNING_TRACK_200M, Sport.RUNNING_TRACK_400M}),
    Sport.WALKING: frozenset({Sport.WALKING_HIKING}),
    Sport.CROSS_COUNTRY_SKIING: frozenset({Sport.CROSS_COUNTRY_SKIING_CLASSIC, Sport.CROSS_COUNTRY_SKIING_SKATE, Sport.CROSS_COUNTRY_SKIING_BACKCOUNTRY, Sport.CROSS_COUNTRY_SKIING_ERGOMETER}),
    Sport.ROWING: frozenset({Sport.ROWING_ERGOMETER, Sport.ROWING_INDOOR, Sport.ROWING_REGATTA, Sport.ROWING_FIXED_SEAT, Sport.ROWING_COASTAL}),
    Sport.SWIMMING: frozenset({Sport.SWIMMING_POOL, Sport.SWIMMING_POOL_50M, Sport.SWIMMING_POOL_25M, Sport.SWIMMING_POOL_25Y, Sport.SWIMMING_POOL_33M, Sport.SWIMMING_OPEN_WATER, Sport.SWIMMING_FLUME}),
    Sport.SWIMMING_POOL: frozenset({Sport.SWIMMING_POOL_50M, Sport.SWIMMING_POOL_25M, Sport.SWIMMING_POOL_25Y, Sport.SWIMMING_POOL_33M}),
}


def classify_sport(
    sport: str | None,
    sub_sport: str | None = None,
    *,
    has_gps: bool = False,
) -> Sport:
    """Map FIT sport/sub_sport strings to a :class:`Sport` category.

    Uses the same heuristics as SweatStack: explicit sub_sport mappings
    where possible, GPS presence as a tiebreaker for indoor/outdoor.
    """
    match sport:
        case "cycling":
            match sub_sport:
                case "indoor_cycling":
                    return Sport.CYCLING_TRAINER
                case "road":
                    return Sport.CYCLING_ROAD
                case "mountain" | "downhill":
                    return Sport.CYCLING_MOUNTAINBIKE
                case "cyclocross":
                    return Sport.CYCLING_CYCLOCROSS
                case "track_cycling":
                    return Sport.CYCLING_TRACK
                case "gravel":
                    return Sport.CYCLING_GRAVEL
                case _:
                    return Sport.CYCLING_ROAD if has_gps else Sport.CYCLING
        case "running":
            match sub_sport:
                case "treadmill":
                    return Sport.RUNNING_TREADMILL
                case "track":
                    return Sport.RUNNING_TRACK
                case "trail":
                    return Sport.RUNNING_TRAIL
                case _:
                    return Sport.RUNNING_ROAD if has_gps else Sport.RUNNING
        case "walking":
            return Sport.WALKING
        case "hiking":
            return Sport.WALKING_HIKING
        case "swimming":
            return Sport.SWIMMING
        case "cross_country_skiing":
            if sub_sport == "skate_skiing":
                return Sport.CROSS_COUNTRY_SKIING_SKATE
            return Sport.CROSS_COUNTRY_SKIING_CLASSIC
        case "rowing":
            if sub_sport == "indoor_rowing":
                return Sport.ROWING_ERGOMETER
            return Sport.ROWING
        case "e_biking":
            return Sport.CYCLING_ROAD if has_gps else Sport.CYCLING
        case "generic":
            return Sport.GENERIC
        case _:
            return Sport.UNKNOWN
